// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Diagnostics.proto

#include "Diagnostics.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
constexpr diagnostics_v1_DiagnosticsEntry_DoNotUse::diagnostics_v1_DiagnosticsEntry_DoNotUse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct diagnostics_v1_DiagnosticsEntry_DoNotUseDefaultTypeInternal {
  constexpr diagnostics_v1_DiagnosticsEntry_DoNotUseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~diagnostics_v1_DiagnosticsEntry_DoNotUseDefaultTypeInternal() {}
  union {
    diagnostics_v1_DiagnosticsEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT diagnostics_v1_DiagnosticsEntry_DoNotUseDefaultTypeInternal _diagnostics_v1_DiagnosticsEntry_DoNotUse_default_instance_;
constexpr diagnostics_v1::diagnostics_v1(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : diagnostics_(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}){}
struct diagnostics_v1DefaultTypeInternal {
  constexpr diagnostics_v1DefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~diagnostics_v1DefaultTypeInternal() {}
  union {
    diagnostics_v1 _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT diagnostics_v1DefaultTypeInternal _diagnostics_v1_default_instance_;
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_Diagnostics_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Diagnostics_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Diagnostics_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Diagnostics_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::diagnostics_v1_DiagnosticsEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::diagnostics_v1_DiagnosticsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::diagnostics_v1_DiagnosticsEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::diagnostics_v1_DiagnosticsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::diagnostics_v1, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::diagnostics_v1, diagnostics_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 7, sizeof(::diagnostics_v1_DiagnosticsEntry_DoNotUse)},
  { 9, -1, sizeof(::diagnostics_v1)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_diagnostics_v1_DiagnosticsEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_diagnostics_v1_default_instance_),
};

const char descriptor_table_protodef_Diagnostics_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021Diagnostics.proto\"{\n\016diagnostics_v1\0225\n"
  "\013diagnostics\030\001 \003(\0132 .diagnostics_v1.Diag"
  "nosticsEntry\0322\n\020DiagnosticsEntry\022\013\n\003key\030"
  "\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001b\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Diagnostics_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Diagnostics_2eproto = {
  false, false, 152, descriptor_table_protodef_Diagnostics_2eproto, "Diagnostics.proto", 
  &descriptor_table_Diagnostics_2eproto_once, nullptr, 0, 2,
  schemas, file_default_instances, TableStruct_Diagnostics_2eproto::offsets,
  file_level_metadata_Diagnostics_2eproto, file_level_enum_descriptors_Diagnostics_2eproto, file_level_service_descriptors_Diagnostics_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_Diagnostics_2eproto_getter() {
  return &descriptor_table_Diagnostics_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_Diagnostics_2eproto(&descriptor_table_Diagnostics_2eproto);

// ===================================================================

diagnostics_v1_DiagnosticsEntry_DoNotUse::diagnostics_v1_DiagnosticsEntry_DoNotUse() {}
diagnostics_v1_DiagnosticsEntry_DoNotUse::diagnostics_v1_DiagnosticsEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void diagnostics_v1_DiagnosticsEntry_DoNotUse::MergeFrom(const diagnostics_v1_DiagnosticsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata diagnostics_v1_DiagnosticsEntry_DoNotUse::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_Diagnostics_2eproto_getter, &descriptor_table_Diagnostics_2eproto_once,
      file_level_metadata_Diagnostics_2eproto[0]);
}

// ===================================================================

class diagnostics_v1::_Internal {
 public:
};

diagnostics_v1::diagnostics_v1(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  diagnostics_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:diagnostics_v1)
}
diagnostics_v1::diagnostics_v1(const diagnostics_v1& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  diagnostics_.MergeFrom(from.diagnostics_);
  // @@protoc_insertion_point(copy_constructor:diagnostics_v1)
}

inline void diagnostics_v1::SharedCtor() {
}

diagnostics_v1::~diagnostics_v1() {
  // @@protoc_insertion_point(destructor:diagnostics_v1)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void diagnostics_v1::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void diagnostics_v1::ArenaDtor(void* object) {
  diagnostics_v1* _this = reinterpret_cast< diagnostics_v1* >(object);
  (void)_this;
  _this->diagnostics_. ~MapField();
}
inline void diagnostics_v1::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena) {
  if (arena != nullptr) {
    arena->OwnCustomDestructor(this, &diagnostics_v1::ArenaDtor);
  }
}
void diagnostics_v1::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void diagnostics_v1::Clear() {
// @@protoc_insertion_point(message_clear_start:diagnostics_v1)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  diagnostics_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* diagnostics_v1::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<string, string> diagnostics = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&diagnostics_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* diagnostics_v1::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:diagnostics_v1)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, string> diagnostics = 1;
  if (!this->_internal_diagnostics().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        (void)p;
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "diagnostics_v1.DiagnosticsEntry.key");
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
          "diagnostics_v1.DiagnosticsEntry.value");
      }
    };

    if (stream->IsSerializationDeterministic() &&
        this->_internal_diagnostics().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_diagnostics().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_diagnostics().begin();
          it != this->_internal_diagnostics().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = diagnostics_v1_DiagnosticsEntry_DoNotUse::Funcs::InternalSerialize(1, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, target, stream);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
          it = this->_internal_diagnostics().begin();
          it != this->_internal_diagnostics().end(); ++it) {
        target = diagnostics_v1_DiagnosticsEntry_DoNotUse::Funcs::InternalSerialize(1, it->first, it->second, target, stream);
        Utf8Check::Check(&(*it));
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:diagnostics_v1)
  return target;
}

size_t diagnostics_v1::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:diagnostics_v1)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<string, string> diagnostics = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_diagnostics_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, std::string >::const_iterator
      it = this->_internal_diagnostics().begin();
      it != this->_internal_diagnostics().end(); ++it) {
    total_size += diagnostics_v1_DiagnosticsEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData diagnostics_v1::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    diagnostics_v1::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*diagnostics_v1::GetClassData() const { return &_class_data_; }

void diagnostics_v1::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message*to,
                      const ::PROTOBUF_NAMESPACE_ID::Message&from) {
  static_cast<diagnostics_v1 *>(to)->MergeFrom(
      static_cast<const diagnostics_v1 &>(from));
}


void diagnostics_v1::MergeFrom(const diagnostics_v1& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:diagnostics_v1)
  GOOGLE_DCHECK_NE(&from, this);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  diagnostics_.MergeFrom(from.diagnostics_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void diagnostics_v1::CopyFrom(const diagnostics_v1& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:diagnostics_v1)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool diagnostics_v1::IsInitialized() const {
  return true;
}

void diagnostics_v1::InternalSwap(diagnostics_v1* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  diagnostics_.InternalSwap(&other->diagnostics_);
}

::PROTOBUF_NAMESPACE_ID::Metadata diagnostics_v1::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_Diagnostics_2eproto_getter, &descriptor_table_Diagnostics_2eproto_once,
      file_level_metadata_Diagnostics_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::diagnostics_v1_DiagnosticsEntry_DoNotUse* Arena::CreateMaybeMessage< ::diagnostics_v1_DiagnosticsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::diagnostics_v1_DiagnosticsEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::diagnostics_v1* Arena::CreateMaybeMessage< ::diagnostics_v1 >(Arena* arena) {
  return Arena::CreateMessageInternal< ::diagnostics_v1 >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
